name: Deploy static site to public Pages repo

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          touch .nojekyll
          echo www.dekorpvc.com > CNAME

      - name: Push to public repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PAGES_TOKEN }}
          repository-name: amgeekz/dekorpvc
          branch: main
          folder: .
          clean: true
